server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: utente_service_route
              uri: lb://UTENTE-SERVICE
              predicates:
                - Path=/utenti/**
              filters:
                - RewritePath=/utenti/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
